// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalPark.Models;

#nullable disable

namespace NationalParks.Solution.Migrations
{
    [DbContext(typeof(NationalParkContext))]
    [Migration("20220819181447_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalPark.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Zion",
                            RegionId = 0,
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "YellowStone",
                            RegionId = 0,
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Sequoia",
                            RegionId = 0,
                            State = "California"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Everglades",
                            RegionId = 0,
                            State = "Florida"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Arches",
                            RegionId = 0,
                            State = "Colorado"
                        });
                });

            modelBuilder.Entity("NationalPark.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "West"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
